services:
  db:
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
  phpmyadmin:
      image: phpmyadmin
      ports:
        - 8080:80
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: password
