server:
  port: 8081

spring:
  web:
    cors:
      allowed-origins:
        - http://localhost:5173
        - http://localhost:3000
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers: "*"
      allow-credentials: true
  application:
    name: 331-backend
  profiles:
    active:
      - db
  datasource:
    url: jdbc:mysql://localhost:3307/selabdb?createDatabaseIfNotExists=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      max-file-size: 10MB

application:
  security:
    jwt:
      secret-key: 609c0a90fef8f8761f886ee56989371e22eaa81f467ad628878a82656fe47a647caab2a6aee59ac66529106f86a72a36a45dc259231344e52e2b48b1a3703b0e
      expiration: 86400000
      refresh-token:
        expiration: 604800000

supabase:
  storage:
    endpoint: https://aotchtwolsmxywyutdka.storage.supabase.co/storage/v1/s3
    endpoint_output: https://aotchtwolsmxywyutdka.storage.supabase.co/storage/v1/object/public
    bucket: test
    region: ap-southeast-1
    accessKey: ca763a14af1b7590437beab86533f9ae
    secretKey: a8be5e4a8c9335287d923c49a07b284fde7ca109a867444bc432268340cdbea0