server:
  port: 8080
spring:
  web:
    cors:
      allowed-origins:
        - http://localhost:5173
        - http://localhost:3000
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers: "*"
      allow-credentials: true
  application:
    security:
      enable: false
      jwt:
        secret-key: 0d5133b90cec79a7f84583d7f9a97c8fa50ca55ed1353db02bf273aaab944dd06dd5a98626480f44fe5498f93bcb15949f389d13d77b89af89fef3643e8c56b5
        expiration: 86400000
        refresh-token:
          expiration: 604800000
    name: 331-backend
  profiles:
    active:
      - db
  datasource:
    url: jdbc:mysql://localhost:3307/selabdb?createDatabaseIfNotExists=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      max-file-size: 10MB
supabase:
  storage:
    endpoint: https://aotchtwolsmxywyutdka.storage.supabase.co/storage/v1/s3
    endpoint_output: https://aotchtwolsmxywyutdka.storage.supabase.co/storage/v1/object/public
    bucket: test
    region: ap-southeast-1
    accessKey: ca763a14af1b7590437beab86533f9ae
    secretKey: a8be5e4a8c9335287d923c49a07b284fde7ca109a867444bc432268340cdbea0